export {default as header_menu} from '../assets/bars-solid.svg'
export {default as Footeremailimg} from '../assets/Email Icon.svg'
export {default as FooterInstaIcon} from '../assets/Instagram.svg'
export {default as FooterYoutubeIcon} from '../assets/YouTube.svg'
export {default as FooterTelegramIcon} from '../assets/telegram.png'
export {default as FooterWhatsapp} from '../assets/whatsapp.svg'
export {default as MainAvatar} from '../assets/Avatar.svg'
export {default as MainJsIcon} from '../assets/Javascript.svg'
export {default as MainHtmlIcon} from '../assets/HTML.svg'
export {default as MainCssIcon} from '../assets/CSS.svg'
export {default as MainThumbnailarrowIcon} from '../assets/View Icon.svg'
export {default as MainReactJSIcon} from '../assets/React JS.svg'
export {default as MainBootstrapIcon} from '../assets/bootstrap-fill.svg'
export {default as MainSassIcon} from '../assets/filetype-sass.svg'
export {default as MainThumbnailimg} from '../assets/Project Thumbnail.svg'
export {default as MainThumbnail2ndimg} from '../assets/2nd Project Thumbnail.svg'
export {default as ProjectSimg} from '../assets/notname.png'
export {default as ProjectSimg2} from '../assets/shop.png'
export {default as ProjectSimg3} from '../assets/sites.png'
export {default as ProjectSimg4} from '../assets/todolist.png'
export {default as AboutMeCheckIcon} from '../assets/check.svg'